version: '3'

services:
  composer:
    image: composer:1.9.1
    restart: 'no'
    volumes:
      - ./:/app

  php:
    image: php:7.4.0-cli-alpine
    restart: 'no'
    working_dir: /app
    volumes:
      - ./:/app
